"""Added the contraints and index

Revision ID: 136e876a6375
Revises: dfcf5ec8800e
Create Date: 2026-06-16 10:24:13.085899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136e876a6375'
down_revision: Union[str, Sequence[str], None] = 'dfcf5ec8800e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'companies', ['company_name'])
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_unique_constraint(None, 'projects', ['project_name'])
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_constraint(None, 'companies', type_='unique')
    # ### end Alembic commands ###
