"""Added oauthid in user model

Revision ID: 27ba9c22ebbb
Revises: a18ff85b857e
Create Date: 2026-06-26 23:42:25.086924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ba9c22ebbb'
down_revision: Union[str, Sequence[str], None] = 'a18ff85b857e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['oauth_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'oauth_id')
    # ### end Alembic commands ###
