"""tableargs typo fix

Revision ID: a18ff85b857e
Revises: bfb006db8331
Create Date: 2026-06-21 18:31:24.159089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a18ff85b857e'
down_revision: Union[str, Sequence[str], None] = 'bfb006db8331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_company_manager', 'companies', ['company_name', 'manager_id'])
    op.create_unique_constraint('unique_company_project', 'projects', ['project_name', 'company_id'])
    op.create_unique_constraint('unique_task_project', 'tasks', ['task_name', 'project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_task_project', 'tasks', type_='unique')
    op.drop_constraint('unique_company_project', 'projects', type_='unique')
    op.drop_constraint('unique_company_manager', 'companies', type_='unique')
    # ### end Alembic commands ###
