"""Added oauthprovider name in user model

Revision ID: df1ab278c76c
Revises: 27ba9c22ebbb
Create Date: 2026-06-27 01:25:13.381705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df1ab278c76c'
down_revision: Union[str, Sequence[str], None] = '27ba9c22ebbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###
