"""Added the Company Model

Revision ID: dfcf5ec8800e
Revises: 4e9abcdff489
Create Date: 2026-06-16 09:51:07.007064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfcf5ec8800e'
down_revision: Union[str, Sequence[str], None] = '4e9abcdff489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('company_description', sa.String(), nullable=True),
    sa.Column('company_banner', sa.String(), nullable=True),
    sa.Column('company_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_id')
    )
    op.add_column('projects', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'projects', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'users', ['company_id'])
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'company_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'company_id')
    op.drop_table('companies')
    # ### end Alembic commands ###
