"""CASCADE DELETE ON USER_COMPANIES TABLE

Revision ID: 0a122c412afe
Revises: af0a48376906
Create Date: 2026-06-17 12:49:15.397542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a122c412afe'
down_revision: Union[str, Sequence[str], None] = 'af0a48376906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_companies_company_id_fkey'), 'user_companies', type_='foreignkey')
    op.drop_constraint(op.f('user_companies_user_id_fkey'), 'user_companies', type_='foreignkey')
    op.create_foreign_key(None, 'user_companies', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_companies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_companies', type_='foreignkey')
    op.drop_constraint(None, 'user_companies', type_='foreignkey')
    op.create_foreign_key(op.f('user_companies_user_id_fkey'), 'user_companies', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_companies_company_id_fkey'), 'user_companies', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###
