"""Added the subtask and blocked task model and field in the task model resp.

Revision ID: 12f5f4adafcc
Revises: 196756c97c51
Create Date: 2026-06-30 10:04:09.007162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f5f4adafcc'
down_revision: Union[str, Sequence[str], None] = '196756c97c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
