"""Added the subtask and blocked task model and field in the task model resp.

Revision ID: 196756c97c51
Revises: fdc32daefc61
Create Date: 2026-06-29 14:01:42.827280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '196756c97c51'
down_revision: Union[str, Sequence[str], None] = 'fdc32daefc61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
