"""Unique subtask name removed

Revision ID: 6182a66a6d7a
Revises: 12f5f4adafcc
Create Date: 2026-06-30 10:26:56.087312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6182a66a6d7a'
down_revision: Union[str, Sequence[str], None] = '12f5f4adafcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('subtasks_sub_task_name_key'), 'subtasks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('subtasks_sub_task_name_key'), 'subtasks', ['sub_task_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
