"""Added the subtask and blocked task model and field in the task model resp.

Revision ID: 91e412e8fbfe
Revises: df1ab278c76c
Create Date: 2026-06-29 10:54:49.037421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e412e8fbfe'
down_revision: Union[str, Sequence[str], None] = 'df1ab278c76c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', name='Sub-Task status'), nullable=True),
    sa.Column('sub_task_name', sa.String(), nullable=False),
    sa.Column('sub_task_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub_task_name', 'task_id', name='Unique subtask per task')
    )
    op.create_table('task_tasks',
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('blocked_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_by_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE')
    )
    op.add_column('tasks', sa.Column('progress', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('unique_task_project'), 'tasks', type_='unique')
    op.create_unique_constraint('Unique task per project', 'tasks', ['task_name', 'project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Unique task per project', 'tasks', type_='unique')
    op.create_unique_constraint(op.f('unique_task_project'), 'tasks', ['task_name', 'project_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('tasks', 'is_blocked')
    op.drop_column('tasks', 'progress')
    op.drop_table('task_tasks')
    op.drop_table('subtasks')
    # ### end Alembic commands ###
