"""manage the cascade delete on assoc table

Revision ID: 9f2a5effdce3
Revises: bdd7bee68d1a
Create Date: 2026-06-21 15:06:55.804560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2a5effdce3'
down_revision: Union[str, Sequence[str], None] = 'bdd7bee68d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_projects_project_id_fkey'), 'user_projects', type_='foreignkey')
    op.drop_constraint(op.f('user_projects_user_id_fkey'), 'user_projects', type_='foreignkey')
    op.create_foreign_key(None, 'user_projects', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_tasks_task_id_fkey'), 'user_tasks', type_='foreignkey')
    op.drop_constraint(op.f('user_tasks_user_id_fkey'), 'user_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'user_tasks', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('user_tasks_user_id_fkey'), 'user_tasks', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_tasks_task_id_fkey'), 'user_tasks', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'user_projects', type_='foreignkey')
    op.drop_constraint(None, 'user_projects', type_='foreignkey')
    op.create_foreign_key(op.f('user_projects_user_id_fkey'), 'user_projects', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_projects_project_id_fkey'), 'user_projects', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
