"""Added the subtask and blocked task model and field in the task model resp.

Revision ID: b710aeaaf4a1
Revises: b49cd10f9270
Create Date: 2026-06-29 12:50:32.351533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b710aeaaf4a1'
down_revision: Union[str, Sequence[str], None] = 'b49cd10f9270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
