"""Added the subtask and blocked task model and field in the task model resp.

Revision ID: cc573a4cdaee
Revises: 91e412e8fbfe
Create Date: 2026-06-29 12:35:22.474115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc573a4cdaee'
down_revision: Union[str, Sequence[str], None] = '91e412e8fbfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'subtasks', ['sub_task_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subtasks', type_='unique')
    # ### end Alembic commands ###
