"""Added the subtask and blocked task model and field in the task model resp.

Revision ID: ee9cf98d8ad8
Revises: b710aeaaf4a1
Create Date: 2026-06-29 12:53:26.693060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9cf98d8ad8'
down_revision: Union[str, Sequence[str], None] = 'b710aeaaf4a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('subtasks_task_id_fkey'), 'subtasks', type_='foreignkey')
    op.create_foreign_key(None, 'subtasks', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subtasks', type_='foreignkey')
    op.create_foreign_key(op.f('subtasks_task_id_fkey'), 'subtasks', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
