"""Nullable false for task_id in subtask

Revision ID: f03dd03c10d3
Revises: 6182a66a6d7a
Create Date: 2026-06-30 11:39:57.644297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03dd03c10d3'
down_revision: Union[str, Sequence[str], None] = '6182a66a6d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subtasks', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subtasks', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
