"""Added the subtask and blocked task model and field in the task model resp.

Revision ID: fdc32daefc61
Revises: ee9cf98d8ad8
Create Date: 2026-06-29 13:28:15.285052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc32daefc61'
down_revision: Union[str, Sequence[str], None] = 'ee9cf98d8ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_blocked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_blocked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
